export const UPDATE_GRID = "UPDATE_GRID";
export const UPDATE_E_GRID = "UPDATE_E_GRID";

//GAME STATE CONSTANTS
export const UPDATE_PLAYSTATE = "UPDATE_PLAYSTATE";
export const UPDATE_TURNS = "UPDATE_TURNS";
export const SET_TOTAL_BOATS = "SET_TOTAL_BOATS";
export const SET_BOARD_SIZE = "SET_BOARD_SIZE";
export const SET_TURN_POSSESSION = "SET_TURN_POSSESSION";
export const SET_MY_HITS = "SET_MY_HITS";
export const SET_ENEMY_HITS = "SET_ENEMY_HITS";
